config/routes.rb
Rails.application.routes.draw do
  devise_for :teams
  root to: 'posts#index'
  resources :teams
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :date, :match, :result, presence: true
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_team!
  #before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @team = Team.find(1)
    @posts = Post.all.order(id: "DESC")
  end

  def new
    @post = Post.new
  end

  def edit
    #@post = Post.find(params[:id])
    @post = Post.find(1)
  end

  def create
    @post = Post.find(1)
    Post.create(post_params)
    #@post = @team.posts.new(post_params)
  end

  def show
    #@post = Post.find(params[:id])
    @team = Team.find(1)
    @post = Post.find(1)
  end

  

  private
  def post_params
    #params.require(:post)
    params.permit(:date, :match, :result, :formation, :num11, :num10, :num9, :num8, :num7, :num6, :num5, :num4, :num3, :num2, :num1)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  protect_from_forgery with: :null_session 
  protect_from_forgery except: :create
  def index
    @posts = Post.all
  end
  
  def edit
    @team = Team.find(params[:id])
  end

  def new
    @team = Team.new
  end

  def update
    if current_user.update(team_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def create
    @team = Team.find(params[:id])
    redirect_to 'index'
  end

  def show
    @posts = Post.all
  end

  private

  def team_params
    params.require(:team).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SOCCER11
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    :javascript
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
  %body
    
    = yield

app/views/layouts/shared/_header.html.haml
.wrapper 
  .header
    .header__log
      soccer11
    .header__message
      自分のチームのフォーメーションを登録しよう
    .contents
      .contents-data
        .myteam
          = @team.name

app/views/layouts/shared/_member.html.haml
.wrapper 
  .header
    .header__log
      soccer11
    .header__message
      自分のチームのフォーメーションを登録しよう
    .contents
      .contents-data
        .myteam
          = @team.name
        .info
          .date
            試合した日
            %br
            = @post.date
          .match
            対戦相手
            %br
            = @post.match
          .result
            試合結果
            %br 
            = @post.result
  .main 
    .contents-formation
      .formation
        %form
          %input#search{placeholder: "Search...", type: "search"}/

app/views/posts/_header.html.haml
.wrapper 
  .head
    .header__logo
      = link_to "SOCCER11", 'root_path', class: "header--title--text"
    .header__message
      自分のチームのフォーメーションを登録しよう
    .header_btn
      = link_to new_team_path, class: "header_new_btn" do
        新規登録
      = link_to new_team_session_path, class: "header_login_btn" do
        ログイン

app/views/posts/create.html.haml
.create-top
%h1 フォーメーションとメンバー登録が完了しました
= link_to 'トップページに戻る', '/posts'

app/views/posts/edit.html.haml
.wrapper 
  = form_with model: @post, class: :form, local: true do |form|
  .head
    .header__logo
      soccer11
    .header__message
      自分のチームのフォーメーションを登録しよう
    .contents
      .contents-data
        .myteam
          <i class="fas fa-tshirt"></i>日本代表
        .infomation
          .date
            %label 試合した日
            = form.text_area :content, pla
            %input#date{name: "date", type: "date", value: ""}/
          .match
            %form{action: "//www-creators.com/rsc/receiver.php", method: "post"}
              %label 対戦相手
              %input#match{maxlength: "10", name: "battle", placeholder: "対戦相手", type: "text", value: ""}/
          .result
            %form{action: "//www-creators.com/rsc/receiver.php", method: "post"}
              %label 試合結果
              %input#result{maxlength: "10", name: "result", placeholder: "試合結果", type: "text", value: ""}/
  .mains
    .contents-formation
      .formation
        .selection
          .fotmation-select
        .formation-fields
          .player
            .switch-contents
              %input#layout-4-4-2{checked: "checked", name: "layout", type: "radio", varue: "4-4-2"}/
              %label{for: "layout-4-4-2"} 4-4-2
              %input#layout-4-5-1{name: "layout", type: "radio", varue: "4-5-1"}/
              %label{for: "layout-4-5-1"} 4-5-1
              %input#layout-4-3-3{name: "layout", type: "radio", varue: "4-3-3"}/
              %label{for: "layout-4-3-3"} 4-3-3
              %input#layout-3-5-2{name: "layout", type: "radio", varue: "3-5-2"}/
              %label{for: "layout-3-5-2"} 3-5-2
              %ul
                  = form.text_area :content, placeholder: :選手名, id: :num11
                  = form.text_area :content, placeholder: :選手名, id: :num10
                  = form.text_area :content, placeholder: :選手名, id: :num9
                  = form.text_area :content, placeholder: :選手名, id: :num8
                  = form.text_area :content, placeholder: :選手名, id: :num7
                  = form.text_area :content, placeholder: :選手名, id: :num6
                  = form.text_area :content, placeholder: :選手名, id: :num5
                  = form.text_area :content, placeholder: :選手名, id: :num4
                  = form.text_area :content, placeholder: :選手名, id: :num3
                  = form.text_area :content, placeholder: :選手名, id: :num2
                  = form.text_area :content, placeholder: :選手名, id: :num1
                  = form.submit '編集する', class: :form__btn


        

app/views/posts/index.html.haml
.header
  = render "header"
.main
  .game_box
    - @posts.each do |post|
      .game-date
        = post.date
      .game-match
        = link_to post.match, post_path(post.id), class: "game-match"
      .game-result
        = post.result

app/views/posts/new.html.haml
= render "header"
.wrapper
  .mains
    .contents-formation
      .formation
        .selection
          .fotmation-select
        .formation-fields
          .player
            .switch-contents
              %input#layout-4-4-2{checked: "checked", name: "layout", type: "radio", varue: "4-4-2"}/
              %label{for: "layout-4-4-2"} 4-4-2
              %input#layout-4-5-1{name: "layout", type: "radio", varue: "4-5-1"}/
              %label{for: "layout-4-5-1"} 4-5-1
              %input#layout-4-3-3{name: "layout", type: "radio", varue: "4-3-3"}/
              %label{for: "layout-4-3-3"} 4-3-3
              %input#layout-3-5-2{name: "layout", type: "radio", varue: "3-5-2"}/
              %label{for: "layout-3-5-2"} 3-5-2
              %ul
                = form_with model: @post, class: :form, local: true do |form|
                  = form.text_area :content, placeholder: :選手名, id: :num11
                  = form.text_area :content, placeholder: :選手名, id: :num10
                  = form.text_area :content, placeholder: :選手名, id: :num9
                  = form.text_area :content, placeholder: :選手名, id: :num8
                  = form.text_area :content, placeholder: :選手名, id: :num7
                  = form.text_area :content, placeholder: :選手名, id: :num6
                  = form.text_area :content, placeholder: :選手名, id: :num5
                  = form.text_area :content, placeholder: :選手名, id: :num4
                  = form.text_area :content, placeholder: :選手名, id: :num3
                  = form.text_area :content, placeholder: :選手名, id: :num2
                  = form.text_area :content, placeholder: :選手名, id: :num1
                  = form.submit '投稿する', class: :form__btn

app/views/posts/show.html.haml
= render "header"
.wrapper 
  .main 
    .contents-formation
      .formation
        //  %input#search{placeholder: "Search...", type: "search"}/
        .under-box
          .member-list
            .lineup
              スターティングメンバー
              %br
              = @post.num1
              %br
              = @post.num2
              %br
              = @post.num3
              %br
              = @post.num4
              %br
              = @post.num5
              %br
              = @post.num6
              %br
              = @post.num7
              %br
              = @post.num8
              %br
              = @post.num9
              %br
              = @post.num10
              %br
              = @post.num11
              %br
              %br
              .button-box
                = link_to "登録ページへ", '/posts/new', class: "button"
                = link_to "編集ページへ", '/posts/edit', class: "button"
          .formation-view     
            .style
              = @post.formation
            %br
            %br
            .fw
              .fw1
                = @post.num11
              %br
              .fw2
                = @post.num10
              %br
            .mf-o
              .mf1
                = @post.num9
              %br
              .mf2
                = @post.num8
              %br
              .mf3
                = @post.num7
              %br
            .mf-d
              .mf4
                = @post.num6
              %br
              .mf5
                = @post.num5
              %br
            .df
              .df1
                = @post.num4
              %br
              .df2
                = @post.num3
              %br
              .df3
                = @post.num2
              %br
            .gk
              = @post.num1
            